POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IklhbUdyb290MyIsImlkIjoiNWRjODZmZDk5YzZmMTUzNzIwZTk3MDY4IiwiaWF0IjoxNTczNDE4OTk0fQ.mnQ8adl_qI6-oD7RwMoGgW78OnD-9375WCKanyEI2vw

{
  "title":"newblog",
  "author":"newAuthor",
  "url":"www.newwebsite.com",
  "likes":10,
  "userId": "5dc89455c00c7f23807b5600"
}